# Generated by Django 6.0.6 on 2026-06-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('leader', 'Leader'), ('rep', 'Class Representative'), ('lecturer', 'Lecturer')], default='student', max_length=20),
        ),
    ]
